apiVersion: v1
kind: ConfigMap
metadata:
  name: user-configmap
  namespace: default
  labels:
    app: user-service
data:
  config.json: |
    {
      "port": {{ .Values.service.port.user  }},
      "enableGinConsoleLog": true,
      "enableGinFileLog": true,
      "Logging": {
        "loglevel": "info",
        "logFilename": "logs/server.log",
        "logMaxSize": 10,
        "logMaxBackups": 10,
        "logMaxAge": 30
      },
      "mgAddrs": "mongodb.service:27017",
      "mgDbName": "userdb",
      "mgDbUsername": "users-admin",
      "mgDbPassword": "1qaz2wsx",
      "jwtSecretPassword": "bruce",
      "issuer": "microservice"
    }