apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
  namespace: default
  labels:
    app: user-service
    version: v1
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      app: user-service
      version: v1
  template:
    metadata:
      {{- with .Values.podAnnotations.userService }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        app: user-service
        version: v1
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      serviceAccountName: user-service-v1
      volumes:
        - name: config-volume
          configMap:
            name: user-configmap # mapping configmap to volume
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          volumeMounts:
            - mountPath: /etc/config # mapping configmap to volume
              name: config-volume
          image: "{{ .Values.image.repository.userService }}:{{ .Values.image.tag.userService | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port.user  }}
              protocol: TCP
          envFrom:
            - configMapRef:
                name: user-configmap
          livenessProbe:
            httpGet:
              path: /liveness
              port: {{ .Values.service.port.user  }}
            initialDelaySeconds: 60
            periodSeconds: 30
            timeoutSeconds: 3
            failureThreshold: 3
            successThreshold: 1
          readinessProbe:
            httpGet:
              path: /health
              port: {{ .Values.service.port.user  }}
            initialDelaySeconds: 60
            periodSeconds: 30
            timeoutSeconds: 3
            failureThreshold: 3
            successThreshold: 1
{{/*          resources:*/}}
{{/*            {{- toYaml .Values.resources | nindent 12 }}*/}}
{{/*      {{- with .Values.nodeSelector }}*/}}
{{/*      nodeSelector:*/}}
{{/*        {{- toYaml . | nindent 8 }}*/}}
{{/*      {{- end }}*/}}
{{/*      {{- with .Values.affinity }}*/}}
{{/*      affinity:*/}}
{{/*        {{- toYaml . | nindent 8 }}*/}}
{{/*      {{- end }}*/}}
{{/*      {{- with .Values.tolerations }}*/}}
{{/*      tolerations:*/}}
{{/*        {{- toYaml . | nindent 8 }}*/}}
{{/*      {{- end }}*/}}
