apiVersion: v1
kind: Service
metadata:
  name: shopping-cart-service
  namespace: default
  labels:
    app: shopping-cart-service
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: shopping-cart-service
