apiVersion: v1
kind: Service
metadata:
  name: shopping-cart-service
  namespace: default
  labels:
    app: shopping-cart-service
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: {{ .Values.service.port.shoppingCart  }}
  selector:
    app: shopping-cart-service
