apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: docdb-external-mesh
spec:
  hosts:
  - {{ .Values.serviceEntry.documentdb.host }}
  ports:
    - name: mongo
      number: 27017
      protocol: MONGO
  location: MESH_EXTERNAL
  resolution: NONE