apiVersion: v1
kind: Service
metadata:
  name: {{ include "redis-test.fullname" . }}
  labels:
    {{- include "redis-test.labels" . | nindent 4 }}
spec:
  ports:
    - port: {{ .Values.service.port }}
      protocol: TCP
      name: redis
  clusterIP: None
  selector:
    {{- include "redis-test.selectorLabels" . | nindent 4 }}

