apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: default
  labels:
    app: redis
spec:
  ports:
    - port: {{ .Values.service.port }}
      protocol: TCP
      name: redis
  clusterIP: None
  selector:
    app: redis