apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-configmap
  namespace: default
data:
  config.json: |
    {
      "port": ":8808",
      "enableGinConsoleLog": true,
      "enableGinFileLog": true,
      "Logging": {
        "loglevel": "info",
        "logFilename": "logs/server.log",
        "logMaxSize": 10,
        "logMaxBackups": 10,
        "logMaxAge": 30
      },
      "mgAddrs": "127.0.0.1:27017",
      "mgDbName": "userdb",
      "mgDbUsername": "users-admin",
      "mgDbPassword": "1qaz2wsx",
      "jwtSecretPassword": "bruce",
      "issuer": "microservice"
    }