apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: {{ .Chart.Name }}
  labels:
    app: {{ .Chart.Name }}
spec:
  host: {{ .Chart.Name }}
  subsets:
    - name: v1
      labels:
        version: v1
