apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ .Chart.Name }}
  labels:
    app: {{ .Chart.Name }}
spec:
  hosts:
    - {{ .Chart.Name }}
  http:
    - route:
      - destination:
          host: {{ .Chart.Name }}
          subset: v1
